import AuthContext from "@/context/AuthContext";
import { ThemeProvider } from "@/context/ThemeProvider";
import { cn } from "@/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Header from "./Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthContext>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body
            className={cn(
              "min-h-screen font-sans antialiased",
              GeistSans.variable,
              GeistMono.variable
            )}>
            <Header />
            <main className={GeistSans.variable}>{children}</main>
          </body>
        </ThemeProvider>
      </AuthContext>
    </html>
  );
}
