services:
  caddy:
    container_name: caddy
    image: "ghcr.io/easyselfhost/caddy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - proxy-net
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
    env_file:
      - .env

  nextapp:
    container_name: nextapp
    image: nextapp1.0.0
    networks:
      - proxy-net
    build:
      context: ./frontend
      target: runner
      network: host
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://goapp:8000
    env_file:
      - .env
    depends_on:
      - goapp

  goapp:
    container_name: goapp
    restart: unless-stopped
    image: goapp1.0.0
    networks:
      - proxy-net
    build:
      context: ./backend
      args:
        ENV: prod
    env_file:
      - .env

    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh -c "go build -buildvcs=false -o ./databeis ./cmd && ./databeis"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    networks:
      - proxy-net
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

networks:
  proxy-net:
