services:
  nextapp:
    container_name: nextapp
    image: nextapp1.0.0
    build:
      context: ./frontend
      target: runner
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - goapp

  goapp:
    container_name: goapp
    image: goapp1.0.0
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: air ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
